name:     hspec-formatters-codewars
version:  0.3.0
github:   "codewars/hspec-formatters-codewars"
license:  MIT
synopsis: Hspec formatter for Codewars

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/codewars/hspec-formatters-codewars#readme>

dependencies:
- base >= 4.7 && < 5
- hspec-core >= 2.8
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  hspec-formatters-codewars-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - hspec >= 2.8
    - hspec-core >= 2.8
    - hspec-formatters-codewars
    - QuickCheck
    - silently
    verbatim:
      build-tool-depends:
        hspec-discover:hspec-discover
